# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_auto_20150826_0831'), ('app', '0003_auto_20150930_1403'), ('app', '0004_app_push_key'), ('app', '0005_responselog'), ('app', '0006_auto_20160422_1233'), ('app', '0007_auto_20160701_0926')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform',
                 models.CharField(choices=[('apns', 'Apple Push Notifications'), ('gcm', 'Google Cloud Messaging')],
                                  max_length=4)),
                ('app_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sip_user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('client_version', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, choices=[('apns', 'Apple Push Notifications'), ('gcm', 'Google Cloud Messaging')], max_length=4, null=True)),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.App')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('token', 'platform')]),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('token', 'app'), ('sip_user_id', 'app')]),
        ),
        migrations.RunSQL(
            sql='UPDATE app_device SET app_id = (SELECT MIN(id) FROM app_app WHERE app_app.platform = app_device.platform);',
            reverse_sql='UPDATE app_device SET app_id = NULL',
        ),
        migrations.AlterField(
            model_name='device',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='platform',
        ),
        migrations.AddField(
            model_name='device',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='sip_user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='app',
            name='push_key',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('app_id', 'platform')]),
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('apns', 'Apple Push Notifications'), ('gcm', 'Google Cloud Messaging'), ('android', 'Android')], max_length=10)),
                ('roundtrip_time', models.FloatField()),
                ('available', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('apns', 'Apple Push Notifications'), ('gcm', 'Google Cloud Messaging'), ('android', 'Android')], max_length=10),
        ),
    ]
