# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0007_auto_20160701_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logentries_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='remote_logging_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
