# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_app_partner_logentries_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='use_apns2',
            field=models.BooleanField(default=False),
        ),
    ]
