# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_use_sip_user_id_as_pk_for_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
    ]
