# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_use_apns2_as_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='use_apns2',
        ),
    ]
