# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160422_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('apns', 'Apple Push Notifications'), ('gcm', 'Google Cloud Messaging'), ('android', 'Android')], max_length=10),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='platform',
            field=models.CharField(choices=[('apns', 'Apple Push Notifications'), ('gcm', 'Google Cloud Messaging'), ('android', 'Android')], max_length=10),
        ),
    ]
